marqo:
  image:
    registry: docker.io
    repo: marqoai/marqo
    tag: 2.10.1
  replicas: 1
  memory: "8G"
  storage: "20Gi"
  gpu_enabled: false

vespa:
  image:
    registry: docker.io
    repo: vespaengine/vespa
    tag: 8.367.14
  configServer:
    replicas: 3
    storage:
      var: "10Gi"
      logs: "10Gi"
      workspace: "10Gi"
    memory:
      requests: "4G"
  contentServer:
    redundancy: 2
    replicas: 2 # must be divisible by the redundancy number above
    storage: "200Gi"
    memory:
      requests: "4G"
  adminServer:
    replicas: 1
    memory:
      requests: "4G"
  feedServer:
   replicas: 1
   memory:
     requests: "4G"
  queryServer:
    replicas: 1
    memory:
      requests: "4G"

